#!/bin/zsh
sudo apt install fzf
sudo apt install fuse
sudo apt install stow

# Node
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
source ~/.bashrc
nvm install node
nvm use node
nvm alias default node
npm install -g yarn

# Nvim
wget https://github.com/neovim/neovim/releases/download/stable/nvim.appimage
chmod u+x ./nvim.appimage
sudo mv nvim.appimage /usr/local/bin/nvim
CUSTOM_NVIM_PATH=/usr/local/bin/nvim
set -u
sudo update-alternatives --install /usr/bin/ex ex "${CUSTOM_NVIM_PATH}" 110
sudo update-alternatives --install /usr/bin/vi vi "${CUSTOM_NVIM_PATH}" 110
sudo update-alternatives --install /usr/bin/view view "${CUSTOM_NVIM_PATH}" 110
sudo update-alternatives --install /usr/bin/vim vim "${CUSTOM_NVIM_PATH}" 110
sudo update-alternatives --install /usr/bin/vimdiff vimdiff "${CUSTOM_NVIM_PATH}" 110

# ZSH
sudo apt install zsh -y
sudo schs -s $(which zsh)
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
git clone https://github.com/zdharma-continuum/fast-syntax-highlighting.git \
   ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/fast-syntax-highlighting
cd ~/dotfiles
rm -rf ~/.zshrc
stow zsh
rm -rf ~/.bashrc
stow bash
curl -sS https://starship.rs/install.sh | sh

# Dotfiles
sudo apt-get install stow
git clone https://github.com/LUSEDOU/dotfiles ~/dotfiles

#Tmux
sudo apt-get install tmux
cd ~/dotfiles
stow -D tmux
stow tmux
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# Git
cd ~/Downloads
LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep -Po '"tag_name": "v\K[^"]*')
curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz"
tar xf lazygit.tar.gz lazygit
sudo install lazygit /usr/local/bin
rm -rf lazygit*
rm -rf ~/.config/lazygit/config.yml
cd ~/dotfiles
stow lazygit

## Utils
sudo apt-get install bat-cat nnn fd-find ripgrep -y
mkdir -p ~/.local/bin
ln -s /ust/bin/batcat ~/.local/bin/bat
curl https://fx.wtf/install.sh | sudo sh
