ln -s ~/dotfiles/.bashrc ~/.bashrc &&
ln -s ~/dotfiles/.zshrc ~/.zshrc &&
ln -s ~/dotfiles/.p10k.zsh ~/.p10k.zsh &&
ln -s ~/dotfiles/my_aliases.zsh  $ZSH_CUSTOM/my_aliases.zsh &&
ln -s ~/dotfiles/my_paths.zsh  $ZSH_CUSTOM/my_paths.zsh &&
ln -s ~/dotfiles/tmux/ ~/.tmux &&
ln -s ~/dotfiles/.tmux.conf ~/.tmux.conf &&
ln -s ~/dotfiles/nvim ~/.config/nvim &&
ln -s ~/dotfiles/git/lazygit.yml ~/.config/lazygit/config.yml &&
